//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer6
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public string Rut { get; set; }
        public string Dig { get; set; }
        public string Nombre { get; set; }
        [Display(Name = "Apellido Paterno")]
        public string Ape_pat { get; set; }
        [Display(Name = "Apellido Materno")]
        public string Ape_mat { get; set; }
        public Nullable<int> Fono1 { get; set; }
        public Nullable<int> Fono2 { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string Nombre_usr { get; set; }
        [Display(Name = "Habilitado")]
        public bool Flg_hab { get; set; }
        [Display(Name = "Eliminado")]
        public bool Flg_elim { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Contrasenha { get; set; }
        public int Id_Pefil { get; set; }
        public int Id_Usua { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
