//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer6
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        [Required]
        public string Rut { get; set; }
        [Required]
        public string Dig { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Ape_pat { get; set; }
        [Required]
        public string Ape_mat { get; set; }
        public Nullable<int> Fono1 { get; set; }
        public Nullable<int> Fono2 { get; set; }
        [Required, StringLength(10)]
        public string Nombre_usr { get; set; }
        public bool Flg_hab { get; set; }
        public bool Flg_elim { get; set; }
        [Required, StringLength(8)]
        public string Contrasenha { get; set; }
        [Required]
        public int Id_Pefil { get; set; }
        public int Id_Usua { get; set; }

        public virtual Perfil Perfil { get; set; }
    }
}
