//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Conductor_vehiculo = new HashSet<Conductor_vehiculo>();
        }
    
        public string Patente { get; set; }
        public string Dig { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Anho { get; set; }
        public int Cilindrada { get; set; }
        public Nullable<double> KmLt { get; set; }
        public int Id_Vehi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conductor_vehiculo> Conductor_vehiculo { get; set; }
    }
}
