//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int Id_viaje { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<double> Km { get; set; }
        public Nullable<int> Valor { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public Nullable<int> IdPasajero { get; set; }
        public string RutConductor { get; set; }
        public int IdEstado { get; set; }
        public string Latitud_des { get; set; }
        public string Longitud_des { get; set; }
        public string Latitud_ori { get; set; }
        public string Longitud_ori { get; set; }
        public string HoraIni { get; set; }
        public string HoraTer { get; set; }
        public Nullable<int> Valor_bndra { get; set; }
        public Nullable<int> Valor_mts { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Conductor Conductor { get; set; }
        public virtual estado estado { get; set; }
    }
}
