//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int Id_viaje { get; set; }
        public Nullable<int> Origen { get; set; }
        public Nullable<int> Destino { get; set; }
        public Nullable<double> Km { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraTermino { get; set; }
        public Nullable<int> IdPasajero { get; set; }
        public string RutConductor { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Conductor Conductor { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Direccion Direccion1 { get; set; }
        public virtual estado estado { get; set; }
    }
}
